version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tyler
      POSTGRES_USER: tyler_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 